### ISSUE TITLE
Uint64Type conversion from raw not working with integers

### ISSUE THREAD

**Issue by christian-herber** [CZ-NIC/yangson#63] opened 2020-11-13 14:14 UTC
The logic for converting raw to uint64 seems wrong. The comment makes sense, but the implementation differs.
```python
        A raw instance may be either string or integer.
        """
        if not isinstance(raw, str) or isinstance(raw, bool):
            return None
```
For actual integers, None is returned because it is not a str. The check for bool does not make sense to me, and also would never be evaluated.
Suggest change to
```python
        A raw instance may be either string or integer.
        """
        if not isinstance(raw, str) and not isinstance(raw, int):
```

**Comment by llhotka** [comment] 2020-11-13 14:51
This is a duplicate of #59, but the docstring needs to be corrected.

The check for `bool` is there because Python happily accepts `True` and `False` in place of integers 1 and 0.

**Closed** 2020-11-13 15:06 UTC
Labels: duplicate

**Comment by christian-herber** [comment] 2020-11-16 07:38
I understand the argumentation regarding the json decoding, but in this case, i do not think it quite fits.
What i am feeding into yangson is not a json, it is a python data object. Similar, but not the same.
If your source of information is YANG data serialized in json, you will have the string encoded 64-bit integer type.

But for other sources, this would not be the case. There are two other IETF encoding (XML and CBOR), and if you would load data instances from there into a python object, you would not get the string encoded integers. This means you would have to do some pre-processing and do the YANG/json decoding first, which is a bit pointless, as Python isn't JavaScript

**Comment by llhotka** [comment] 2020-11-16 12:12
Yes, but _raw value_ is defined as the parsed JSON data, see [Glossary](https://yangson.labs.nic.cz/glossary.html). If you already have a Python value, then you could probably set it as the value of `InstanceNode`, and validate if if necessary.
